# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{stalker}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jannis Hermanns"]
  s.date = %q{2011-10-10}
  s.default_executable = %q{stalk}
  s.description = %q{Takes the javascript of stalker and provides the stalker command that uses node to run stalker.js}
  s.email = %q{jannis@gmail.com}
  s.executables = ["stalk"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitmodules",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/stalk",
    "lib/stalker-gem.rb",
    "stalker.gemspec",
    "test/helper.rb",
    "test/test_stalker-gem.rb",
    "vendor/stalker/lib/example_parser.js",
    "vendor/stalker/lib/object_compare.js",
    "vendor/stalker/lib/shout.js",
    "vendor/stalker/lib/stalker.js",
    "vendor/stalker/lib/var_parser.js",
    "vendor/stalker/stalk.js",
    "vendor/stalker/vendor/multipartform.js",
    "vendor/stalker/vendor/restler.js",
    "vendor/stalker/vendor/underscore-min.js"
  ]
  s.homepage = %q{http://github.com/jayniz/stalker-gem}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Installs stalker for you and adds a convenient stalker command}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

